# Generated by Django 4.2 on 2025-05-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent_ui', '0002_appicon_customappmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color_code', models.CharField(default='#5D93E1', max_length=7)),
            ],
            options={
                'verbose_name': 'App Category',
                'verbose_name_plural': 'App Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appicon',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('unknown', 'Unknown Risk')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='appicon',
            name='risk_reasons',
            field=models.TextField(blank=True, help_text='Reasons for the risk classification', null=True),
        ),
        migrations.AlterField(
            model_name='appicon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_ui.appcategory'),
        ),
    ]
