# Generated by Django 4.2 on 2025-05-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_ui', '0003_appcategory_appicon_risk_level_appicon_risk_reasons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcategory',
            options={'verbose_name_plural': 'App Categories'},
        ),
        migrations.AlterModelOptions(
            name='appicon',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customappmapping',
            options={},
        ),
        migrations.RemoveField(
            model_name='appicon',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='customappmapping',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customappmapping',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='appcategory',
            name='color_code',
            field=models.CharField(default='#CCCCCC', max_length=10),
        ),
        migrations.AlterField(
            model_name='appcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appicon',
            name='friendly_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appicon',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='app_icons/'),
        ),
        migrations.AlterField(
            model_name='appicon',
            name='package_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='appicon',
            name='risk_reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customappmapping',
            name='custom_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customappmapping',
            name='package_name',
            field=models.CharField(max_length=200),
        ),
    ]
