# Generated by Django 4.2 on 2025-04-05 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusagelog',
            name='duration',
            field=models.PositiveIntegerField(default=3600, help_text='Duration in seconds'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BlockedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.childdevice')),
            ],
            options={
                'unique_together': {('device', 'app_name')},
            },
        ),
    ]
