# Generated by Django 4.2 on 2025-04-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appusagelog_duration_blockedapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdevice',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
