# Generated by Django 4.2 on 2025-04-27 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blockedapp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='childdevice',
            name='device_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='childdevice',
            unique_together={('parent', 'device_id')},
        ),
    ]
