# Generated by Django 4.2 on 2025-04-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_childdevice_created_at_alter_childdevice_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screentimerule',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='screentimerule',
            name='bedtime_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screentimerule',
            name='bedtime_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
