# Generated by Django 4.2 on 2025-04-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_screentimerule_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('minutes', models.PositiveIntegerField(default=1)),
                ('sync_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_time_entries', to='api.childdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('device', 'timestamp')},
            },
        ),
    ]
