# Generated by Django 4.2 on 2025-05-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_screentime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusagelog',
            name='package_name',
            field=models.CharField(blank=True, help_text='Android package name (e.g., com.whatsapp)', max_length=200, null=True),
        ),
    ]
