# Generated by Django 4.2 on 2025-05-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_appusagelog_package_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusagelog',
            name='package_name',
        ),
        migrations.AddConstraint(
            model_name='appusagelog',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start_time'),
        ),
    ]
