# Generated by Django 4.2 on 2025-06-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_appusagelog_package_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdevice',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
