# Generated by Django 4.2 on 2025-06-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_blockedurl_safebrowsingcategory_urlaccesslog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOfflineNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_sent_at', models.DateTimeField(auto_now_add=True)),
                ('days_offline', models.PositiveIntegerField()),
                ('email_sent_to', models.EmailField(max_length=254)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_notifications', to='api.childdevice')),
            ],
            options={
                'ordering': ['-notification_sent_at'],
            },
        ),
    ]
