# Generated by Django 4.2 on 2025-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20250612_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='screentimerule',
            name='is_timer_active',
            field=models.BooleanField(default=False, help_text='Whether the timer-based limit is currently active'),
        ),
        migrations.AddField(
            model_name='screentimerule',
            name='limit_end_time',
            field=models.DateTimeField(blank=True, help_text='When the current limit will end', null=True),
        ),
        migrations.AddField(
            model_name='screentimerule',
            name='limit_start_time',
            field=models.DateTimeField(blank=True, help_text='When the current limit period started', null=True),
        ),
    ]
