# Generated by Django 4.2 on 2025-06-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_timer_fields_to_screentime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screentimerule',
            name='is_timer_active',
        ),
        migrations.RemoveField(
            model_name='screentimerule',
            name='limit_end_time',
        ),
        migrations.RemoveField(
            model_name='screentimerule',
            name='limit_start_time',
        ),
        migrations.DeleteModel(
            name='DeviceOfflineNotification',
        ),
    ]
