# Generated by Django 4.2 on 2025-06-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_screentimerule_is_timer_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screentimerule',
            name='synced_to_device',
            field=models.BooleanField(default=False),
        ),
    ]
