const packageMapping = {
    // Social Media
    'com.whatsapp': 'WhatsApp',
    'com.whatsapp.w4b': 'WhatsApp Business',
    'com.facebook.katana': 'Facebook',
    'com.facebook.lite': 'Facebook Lite',
    'com.facebook.orca': 'Messenger',
    'com.facebook.mlite': 'Messenger Lite',
    'com.instagram.android': 'Instagram',
    'com.instagram.lite': 'Instagram Lite',
    'com.snapchat.android': 'Snapchat',
    'com.twitter.android': 'Twitter',
    'com.discord': 'Discord',
    'org.telegram.messenger': 'Telegram',
    'org.thunderdog.challegram': 'Telegram X',
    'com.zhiliaoapp.musically': 'TikTok',
    'com.reddit.frontpage': 'Reddit',
    'com.linkedin.android': 'LinkedIn',
    'com.pinterest': 'Pinterest',
    'kik.android': 'Kik',
    'com.tumblr': 'Tumblr',
    'com.skype.raider': 'Skype',
    'com.viber.voip': 'Viber',
    'jp.naver.line.android': 'LINE',
    'com.kakao.talk': 'KakaoTalk',
    'com.imo.android.imoim': 'IMO',
    'com.wechat': 'WeChat',
    'com.vkontakte.android': 'VK',
    'com.biglybt.android.client': 'BiglyBT',
    'com.clubhouse.app': 'Clubhouse',
    'com.tinder': 'Tinder',
    'com.bumble.app': 'Bumble',
    'com.trello': 'Trello',
    
    // Google Apps
    'com.google.android.youtube': 'YouTube',
    'com.google.android.apps.youtube.music': 'YouTube Music',
    'com.google.android.apps.photos': 'Google Photos',
    'com.google.android.gm': 'Gmail',
    'com.google.android.googlequicksearchbox': 'Google',
    'com.google.android.apps.maps': 'Google Maps',
    'com.google.android.apps.docs': 'Google Drive',
    'com.google.android.apps.docs.editors.docs': 'Google Docs',
    'com.google.android.apps.docs.editors.sheets': 'Google Sheets',
    'com.google.android.apps.docs.editors.slides': 'Google Slides',
    'com.google.android.apps.tachyon': 'Google Meet',
    'com.google.android.keep': 'Google Keep',
    'com.google.android.apps.translate': 'Google Translate',
    'com.google.android.calendar': 'Google Calendar',
    'com.google.android.contacts': 'Google Contacts',
    'com.google.android.apps.messaging': 'Google Messages',
    'com.google.android.deskclock': 'Clock',
    'com.google.android.dialer': 'Phone',
    'com.google.android.apps.wellbeing': 'Digital Wellbeing',
    'com.google.android.apps.authenticator2': 'Google Authenticator',
    'com.google.android.apps.nbu.files': 'Files by Google',
    'com.google.android.apps.adm': 'Find My Device',
    'com.google.android.apps.podcasts': 'Google Podcasts',
    'com.google.android.apps.recorder': 'Recorder',
    'com.google.android.apps.magazines': 'Google News',
    'com.google.android.apps.subscriptions.red': 'Google One',
    
    // Microsoft Apps
    'com.microsoft.office.outlook': 'Outlook',
    'com.microsoft.office.word': 'Word',
    'com.microsoft.office.excel': 'Excel',
    'com.microsoft.office.powerpoint': 'PowerPoint',
    'com.microsoft.office.onenote': 'OneNote',
    'com.microsoft.skydrive': 'OneDrive',
    'com.microsoft.teams': 'Microsoft Teams',
    'com.microsoft.office.officehubrow': 'Microsoft Office',
    'com.microsoft.bing': 'Bing',
    'com.microsoft.emmx': 'Microsoft Edge',
    
    // Shopping
    'com.amazon.mShop.android.shopping': 'Amazon',
    'com.ebay.mobile': 'eBay',
    'com.alibaba.aliexpresshd': 'AliExpress',
    'com.walmart.android': 'Walmart',
    'com.wish.android': 'Wish',
    'com.target.ui': 'Target',
    'com.etsy.android': 'Etsy',
    'com.contextlogic.wish': 'Wish',
    'com.shopee.id': 'Shopee',
    'com.shein.shein': 'SHEIN',
    'jumia.android': 'Jumia',
    
    // Entertainment
    'com.spotify.music': 'Spotify',
    'com.netflix.mediaclient': 'Netflix',
    'com.amazon.avod.thirdpartyclient': 'Prime Video',
    'com.hbo.hbonow': 'HBO Max',
    'com.disney.disneyplus': 'Disney+',
    'com.showtime.standalone': 'Showtime',
    'tv.twitch.android.app': 'Twitch',
    'com.pandora.android': 'Pandora',
    'com.apple.android.music': 'Apple Music',
    'com.aspiro.tidal': 'Tidal',
    'com.hulu.plus': 'Hulu',
    'com.netflix.android': 'Netflix',
    'com.crunchyroll.crunchyroid': 'Crunchyroll',
    'com.cbs.app': 'CBS',
    'com.vimeo.android.videoapp': 'Vimeo',
    'com.plexapp.android': 'Plex',
    'com.soundcloud.android': 'SoundCloud',
    'com.peacocktv.peacockandroid': 'Peacock TV',
    'com.discoveryplus.mobile': 'Discovery+',
    'deezer.android.app': 'Deezer',
    'com.spotify.tv.android': 'Spotify TV',
    'com.mxtech.videoplayer.ad': 'MX Player',
    'com.audible.application': 'Audible',
    
    // Travel & Transportation
    'com.ubercab': 'Uber',
    'com.ubercab.eats': 'Uber Eats',
    'com.airbnb.android': 'Airbnb',
    'com.lyft.android': 'Lyft',
    'com.yelp.android': 'Yelp',
    'com.tripadvisor.tripadvisor': 'TripAdvisor',
    'com.booking': 'Booking.com',
    'com.expedia.bookings': 'Expedia',
    'com.waze': 'Waze',
    'com.citymapper.app.release': 'Citymapper',
    'com.doordash.driverapp': 'DoorDash Driver',
    'com.doordash.consumer': 'DoorDash',
    'com.grubhub.android': 'Grubhub',
    'com.postmates.android': 'Postmates',
    
    // Finance
    'com.venmo': 'Venmo',
    'com.paypal.android.p2pmobile': 'PayPal',
    'com.squareup.cash': 'Cash App',
    'com.robinhood.android': 'Robinhood',
    'com.chase.sig.android': 'Chase',
    'com.wf.wellsfargomobile': 'Wells Fargo',
    'com.infonow.bofa': 'Bank of America',
    'com.coinbase.android': 'Coinbase',
    'org.wordpress.android': 'WordPress',
    'com.mint': 'Mint',
    'com.scb.phone': 'Standard Chartered',
    
    // Productivity
    'com.android.chrome': 'Chrome',
    'com.brave.browser': 'Brave Browser',
    'org.mozilla.firefox': 'Firefox',
    'com.opera.browser': 'Opera',
    'com.opera.mini.native': 'Opera Mini',
    'com.duckduckgo.mobile.android': 'DuckDuckGo',
    'com.evernote': 'Evernote',
    'com.todoist': 'Todoist',
    'com.anydo': 'Any.do',
    'com.notion.android': 'Notion',
    'com.dropbox.android': 'Dropbox',
    'com.adobe.reader': 'Adobe Reader',
    'com.adobe.scan.android': 'Adobe Scan',
    'com.adobe.psmobile': 'Adobe Photoshop Express',
    'com.adobe.lrmobile': 'Adobe Lightroom',
    'com.adobe.premiererush.videoeditor': 'Adobe Premiere Rush',
    'com.shazam.android': 'Shazam',
    'com.duolingo': 'Duolingo',
    
    // Games
    'com.mojang.minecraftpe': 'Minecraft',
    'com.supercell.clashofclans': 'Clash of Clans',
    'com.supercell.clashroyale': 'Clash Royale',
    'com.king.candycrushsaga': 'Candy Crush Saga',
    'com.rovio.angrybirds': 'Angry Birds',
    'com.kiloo.subwaysurf': 'Subway Surfers',
    'com.epicgames.fortnite': 'Fortnite',
    'com.garena.game.kgid': 'Free Fire',
    'com.pubg.mobile': 'PUBG Mobile',
    'com.activision.callofduty.shooter': 'Call of Duty Mobile',
    'com.tencent.ig': 'PUBG Mobile',
    'com.roblox.client': 'Roblox',
    
    // System Apps
    'com.android.settings': 'Settings',
    'com.android.vending': 'Play Store',
    'com.sec.android.app.launcher': 'Samsung Launcher',
    'com.android.dialer': 'Phone',
    'com.android.mms': 'Messages',
    'com.android.contacts': 'Contacts',
    'com.android.camera': 'Camera',
    'com.android.gallery3d': 'Gallery',
    'com.google.android.permissioncontroller': 'Permissions',
    'com.android.documentsui': 'Files',
    'com.xiaomi.mipicks': 'GetApps',
    'com.mi.android.globalFileexplorer': 'Mi File Manager',
    'com.huawei.appmarket': 'AppGallery',
    
    // Other Popular Apps
    'org.wikipedia': 'Wikipedia',
    'com.fitbit.FitbitMobile': 'Fitbit',
    'com.samsung.android.app.health': 'Samsung Health',
    'com.weather.Weather': 'Weather Channel',
    'com.gojek.app': 'Gojek',
    'com.grabapp.passenger': 'Grab',
    'com.qqgame.hlddz': 'Happy Poker',
    'co.seedlegals.mobile': 'SeedLegals',
    'com.ss.android.ugc.trill': 'TikTok Lite',
    'org.thoughtcrime.securesms': 'Signal',
    'im.vector.app': 'Element',
    'io.homeassistant.companion.android': 'Home Assistant',
    'org.torproject.android': 'Tor Browser',
    'com.ichi2.anki': 'AnkiDroid',
    'eu.faircode.netguard': 'NetGuard',
    'net.osmand.plus': 'OsmAnd+'
};
